version: '2' #docker-composeのバージョンを指定
services:
  se18g2_db:
    image: mysql:5.6
    ports:
    - "3336:3306"
    environment:
      MYSQL_DATABASE: trendmatch
      MYSQL_USER: se18g2
      MYSQL_PASSWORD: Trend_match1
    hostname: se18g2_db
    volumes:
    -  "./init:/docker-entrypoint-initdb.d"

networks:
  default:
    external:
      name: onyx
